<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <!--TODO: Add specifaction pattern for remove entity framework dependency-->
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.7" />
  </ItemGroup>

</Project>
