<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SharpKml.Core" Version="6.0.0" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\SharedKernel\SharedKernel.csproj" />
	</ItemGroup>
</Project>
