// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payments.Infrastructure.Persistence;

#nullable disable

namespace Payments.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Payments.Domain.Entities.BankQr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("BankAccountNumber")
                        .HasColumnType("int");

                    b.Property<int>("BankAccountType")
                        .HasColumnType("int");

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedQrString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("QrId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BankQrs");
                });

            modelBuilder.Entity("Payments.Domain.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Payments.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("BankQrId")
                        .HasColumnType("int");

                    b.Property<int?>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankQrId");

                    b.HasIndex("BillId");

                    b.ToTable("Payments");

                    b.HasDiscriminator<int>("PaymentMethod");
                });

            modelBuilder.Entity("Payments.Domain.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityUsed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidSince")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("Payments.Domain.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataSyncedSince")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastRunAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Payments.Domain.Entities.QrPayment", b =>
                {
                    b.HasBaseType("Payments.Domain.Entities.Payment");

                    b.Property<Guid>("BankPayId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BankPayId");

                    b.Property<int?>("BankQrId1")
                        .HasColumnType("int");

                    b.Property<int?>("BillId1")
                        .HasColumnType("int");

                    b.Property<string>("PayerAccountNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayerAccountNumber");

                    b.Property<string>("PayerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PayerName");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VoucherNumber");

                    b.HasIndex("BankQrId1");

                    b.HasIndex("BillId1");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Payments.Domain.Entities.VoucherPayment", b =>
                {
                    b.HasBaseType("Payments.Domain.Entities.Payment");

                    b.Property<int?>("BillId1")
                        .HasColumnType("int")
                        .HasColumnName("VoucherPayment_BillId1");

                    b.Property<int?>("VoucherId1")
                        .HasColumnType("int");

                    b.HasIndex("BillId1");

                    b.HasIndex("VoucherId1");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Payments.Domain.Entities.BankQr", b =>
                {
                    b.HasOne("Payments.Domain.Entities.Bill", "Bill")
                        .WithMany("BankQrs")
                        .HasForeignKey("BillId");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Payments.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Payments.Domain.Entities.BankQr", null)
                        .WithMany("Payments")
                        .HasForeignKey("BankQrId");

                    b.HasOne("Payments.Domain.Entities.Bill", null)
                        .WithMany("Payments")
                        .HasForeignKey("BillId");
                });

            modelBuilder.Entity("Payments.Domain.Entities.QrPayment", b =>
                {
                    b.HasOne("Payments.Domain.Entities.BankQr", null)
                        .WithMany("QrPayments")
                        .HasForeignKey("BankQrId1");

                    b.HasOne("Payments.Domain.Entities.Bill", null)
                        .WithMany("QrPayments")
                        .HasForeignKey("BillId1");
                });

            modelBuilder.Entity("Payments.Domain.Entities.VoucherPayment", b =>
                {
                    b.HasOne("Payments.Domain.Entities.Bill", null)
                        .WithMany("VoucherPayments")
                        .HasForeignKey("BillId1");

                    b.HasOne("Payments.Domain.Entities.Voucher", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId1");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("Payments.Domain.Entities.BankQr", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("QrPayments");
                });

            modelBuilder.Entity("Payments.Domain.Entities.Bill", b =>
                {
                    b.Navigation("BankQrs");

                    b.Navigation("Payments");

                    b.Navigation("QrPayments");

                    b.Navigation("VoucherPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
