# Api
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: "#{{Namespace}}#"
type: Opaque
stringData:
  sqlAdministratorPassword: "#{{sqlAdministratorPassword}}#"
  serverFullyQualifiedName: "#{{serverFullyQualifiedName}}#"
  # AppSettings
  ConnectionStrings__DeliveryDb: "#{{ConnectionStringsDeliveryDb}}#"
  ConnectionStrings__PaymentsDb: "#{{ConnectionStringsPaymentsDb}}#"
  TookanCourierConfig__ApiKey: "#{{TookanCourierConfigApiKey}}#"
  FassilAzureAd__Secret: "#{{FassilAzureAdSecret}}#"
  # Auth0__AuthenticationApi__ClientSecret: "#{{Auth0AuthenticationApiClientSecret}}#"
  ApplicationInsights__ClientSecret: "#{{ApplicationInsightsClientSecret}}#"
  GoogleMapsConfig__ApiKey: "#{{GoogleMapsConfigApiKey}}#"
  TookanCourierConfig__ApiKey: "#{{TookanCourierConfigApiKey}}#"
  TookanCourierConfig__SharedSecret: "#{{TookanCourierConfigSharedSecret}}#"
