apiVersion: v1
kind: Service
metadata:
  name: apidelivery-service
  namespace: "#{{Namespace}}#"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apidelivery-deployment
    app.kubernetes.io/component: apidelivery
    app.kubernetes.io/part-of: "#{{Namespace}}#"
  ports:
  - targetPort: 8080
    #puerto de la imagen
    port: 8080
    #puerto de servicio
    nodePort: #{{NodePortApiDelivery}}#
---
apiVersion: v1
kind: Service
metadata:
  name: apipayments-service
  namespace: "#{{Namespace}}#"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apipayments-deployment
    app.kubernetes.io/component: apipayments
    app.kubernetes.io/part-of: "#{{Namespace}}#"
  ports:
  - targetPort: 8080
    #puerto de la imagen
    port: 8080
    #puerto de servicio
    nodePort: #{{NodePortApiPayments}}#
---
