using System;
using System.Collections.Generic;
using Delivery.Domain.Dtos;

namespace Delivery.Infrastructure.Services.Tookan;

public class TookanCreatePickupAndDeliveryTaskContract
{
    // Required
    public string job_pickup_phone { get; set; }
    public string job_pickup_name { get; set; }
    public string job_description { get; set; }
    public string job_pickup_address { get; set; }
    public string job_pickup_latitude { get; set; }
    public string job_pickup_longitude { get; set; }
    public string customer_phone { get; set; }
    public string customer_address { get; set; }
    public string latitude { get; set; }
    public string longitude { get; set; }
    // Optional
    public string job_pickup_email { get; set; }
    // public string customer_email { get; set; }  } // opcional no lo vamos a mandar
    public string customer_username { get; set; } // opcional

    // public string custom_field_template { get; set; } // TODO ??
    // public List<MetaData> meta_data { get; set; } // por ejemplo precio y cantidad
    // public string pickup_custom_field_template { get; set; } // TODO ??
    // public List<MetaData> pickup_meta_data { get; set; } // TODO ??
    // public List<string> p_ref_images { get; set; } // sería bueno tenerlo (Pickup) This is an array of strings containing links of images.
    // public string tags { get; set; } // TODO ?? 	This is a string containing comma separated tags as filters for agents in auto assignment.
    // Generated by Delivery.API
    public string order_id { get; set; }

    // Generated by Delivery.Infrastructure
    public string job_pickup_datetime { get; set; } // TODO ??
    public string job_delivery_datetime { get; set; } //TODO ??

    // Constants
    public string auto_assignment { get; set; }
    public int tracking_link { get; set; }
    public int ride_type { get; set; }
    // public int notify { get; set; } // TODO ?? This is used to enable the notifications.
    // public int geofence { get; set; } // TODO ?? 	This is used to enable the geofencing.
    // Fixed for DeliveryAndPickup
    public string layout_type { get; set; }
    public string has_pickup { get; set; }
    public string has_delivery { get; set; }
    // Fixed
    public string timezone { get; set; }
    public string api_key { get; set; }
    public string team_id { get; set; }

    // Wont use
    // public string fleet_id { get; set; } // opcional va a ser autoasignado, esto no mandamos a tookan
    // public List<string> ref_images { get; set; }
}
public class MetaData
{
    public string label { get; set; }
    public string data { get; set; }
}

public class TookanCreatePickupAndDeliveryTaskResponse
{
    public string pickup_tracking_link { get; set; }
    public string delivery_tracing_link { get; set; }
    public int job_id { get; set; }
    public string job_token { get; set; }
    public string pickup_hash { get; set; }
    public string delivery_hash { get; set; }
    public string customer_name { get; set; }
    public string customer_address { get; set; }
    // "geofence_details": [{
    //     "region_id": 5215,
    //     "region_name": "CHD"
    //     }],
}
public class TookanGenericResponse<T>
{
    public string message { get; set; }
    public int status { get; set; }
    public T data { get; set; }
}

public class TookanGenericListResponse<T>
{
    public string message { get; set; }
    public int status { get; set; }
    public List<T> data { get; set; }
}


public class TookanGetTaskDetailsCommand
{
    public string api_key { get; set; }
    public IEnumerable<string> job_ids { get; set; }
    public int include_task_history { get; set; } = 1;
    public int job_additional_info { get; set; } = 1;
}

public class TookanGetTaskDetailsResponse
{
    public int job_id { get; set; }
    public int? fleet_id { get; set; }
    public TookanJobStatus job_status { get; set; }
    public string order_id { get; set; }
    public bool open_tracking_link { get; set; }
    public string started_datetime { get; set; }
    public string arrived_datetime { get; set; }
    public string completed_datetime { get; set; }
    public string acknowledged_datetime { get; set; }
    public List<TookanTaskHistory> task_history { get; set; }
}

public class TookanTaskHistory
{
    public string description { get; set; }
    public DateTime creation_datetime { get; set; }
}


public class TookanGetAgentsRequest
{
    public string api_key { get; set; }
}

public class TookanGetAgentsResponse
{
    public int fleet_id { get; set; }
    public int device_type { get; set; }
    public int total_rating { get; set; }
    public int total_rated_tasks { get; set; }
    public bool is_active { get; set; }
    public bool has_gps_accuracy { get; set; }
    public string username { get; set; }
    public string name { get; set; }
    public string login_id { get; set; }
    // public string transport_type { get; set; }
    public string transport_desc { get; set; }
    public string license { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public int battery_level { get; set; }
    // public int registration_status { get; set; }
    public string latitude { get; set; }
    public bool is_available { get; set; }
    public string longitude { get; set; }
    public string tags { get; set; }
    public string fleet_thumb_image { get; set; }
    public string fleet_image { get; set; }
    public bool status { get; set; } // 0 free, 1 busy
}
